### ISSUE TITLE
Aaru can't open TOC/CUE image when it uses an absolute path for a BIN when the BIN has been moved

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#451] opened 2020-11-17 22:54 UTC
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit
* [ ] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
    * **Image format**:  TOC
    * **Application that created the image**:
* [ ] I was converting the image...
    * ...**Destination image format**:
* [ ] I was listing the filesystem contents...
* [ ] I was extracting the filesystem contents...
    * ...**Filesystem**:
    * [ ] Analyze command recognizes the filesystem
* [ ] I was creating a metadata sidecar
* [ ] I was checksumming the image
* [ ] I was verifying the image

### Description

When trying to open a TOC/CUE image that specifies and absolute path for the BIN when the BIN has been moved, Aaru is unable to read the image.

### Exact command line used:

`aaru -d i info .\TOC-CDRDAO.TOC`

### Output of command execution with debug output enabled
```
aaru 5.1.99.3216+a7e483ba built by DESKTOP-TUVQ3CV in Debug, modified
Copyright c 2011-2020 Natalia Portillo

Image format identified by CDRDAO tocfile (04d7ba12-1be8-44d4-97a4-1b48a505463e).

Exception trying to identify image file Aaru.Filters.ZZZNoFilter
Exception: Object reference not set to an instance of an object.
Stack trace:    at Aaru.DiscImages.Cdrdao.Open(IFilter imageFilter) in G:\GIT\Aaru-dps\Aaru\Aaru.Images\CDRDAO\Read.cs:line 651
Unable to open image format
No error given
Uploading statistics
PS G:\GIT\Aaru-dps\Aaru\Aaru\bin\Debug\netcoreapp3.1> ./aaru -d i info .\TOC-CDRDAO.TOC
aaru 5.1.99.3216+a7e483ba built by DESKTOP-TUVQ3CV in Debug, modified
Copyright c 2011-2020 Natalia Portillo

DEBUG (Analyze command): --debug=True
DEBUG (Analyze command): --input=.\TOC-CDRDAO.TOC
DEBUG (Analyze command): --verbose=False
DEBUG (Format detection): Trying plugin Aaru Format
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 1381975107
DEBUG (Anex86 plugin): fdihdr.hddtype = 168447311
DEBUG (Anex86 plugin): fdihdr.hdrSize = 539963146
DEBUG (Anex86 plugin): fdihdr.dskSize = 1667330644
DEBUG (Anex86 plugin): fdihdr.bps = 170991723
DEBUG (Anex86 plugin): fdihdr.spt = 1128354388
DEBUG (Anex86 plugin): fdihdr.heads = 1330454603
DEBUG (Anex86 plugin): fdihdr.cylinders = 1597064516
DEBUG (Format detection): Trying plugin Apple ][ Interleaved Disk Image
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
DEBUG (Format detection): Trying plugin CDRDAO tocfile
Image format identified by CDRDAO tocfile (04d7ba12-1be8-44d4-97a4-1b48a505463e).

DEBUG (CDRDAO plugin): Found CD_ROM at line 1
DEBUG (CDRDAO plugin): Found TRACK type "MODE1_RAW" with no subchannel at line 5
DEBUG (CDRDAO plugin): Found NO COPY at line 6
DEBUG (CDRDAO plugin): Found DATAFILE "E:/Installers/XDuplicator/TOC-CDRDAO.BIN" at line 7
DEBUG (CDRDAO plugin): Disc image parsing results
DEBUG (CDRDAO plugin): Disc CD-TEXT:
DEBUG (CDRDAO plugin):  Arranger is not set.
DEBUG (CDRDAO plugin):  Composer is not set.
DEBUG (CDRDAO plugin):  Performer is not set.
DEBUG (CDRDAO plugin):  Songwriter is not set.
DEBUG (CDRDAO plugin):  Title is not set.
DEBUG (CDRDAO plugin): Disc information:
DEBUG (CDRDAO plugin):  Guessed disk type: CDROM
DEBUG (CDRDAO plugin):  Barcode not set.
DEBUG (CDRDAO plugin):  Disc ID not set.
DEBUG (CDRDAO plugin):  MCN not set.
DEBUG (CDRDAO plugin):  Comment not set.
DEBUG (CDRDAO plugin): Track information:
DEBUG (CDRDAO plugin):  Disc contains 1 tracks
DEBUG (CDRDAO plugin):  Track 1 information:
DEBUG (CDRDAO plugin):          2352 bytes per sector
DEBUG (CDRDAO plugin):          Pregap: 0 sectors
DEBUG (CDRDAO plugin):          Data: 1053 sectors starting at sector 0
DEBUG (CDRDAO plugin):          Postgap: 0 sectors
Exception trying to identify image file Aaru.Filters.ZZZNoFilter
Exception: Object reference not set to an instance of an object.
Stack trace:    at Aaru.DiscImages.Cdrdao.Open(IFilter imageFilter) in G:\GIT\Aaru-dps\Aaru\Aaru.Images\CDRDAO\Read.cs:line 651
Unable to open image format
No error given
```

### Image

[451.zip](https://github.com/aaru-dps/Aaru/files/5556679/451.zip)

**Comment by claunia** [comment] 2021-06-07 12:39
Duplicate of #214

**Closed by claunia** 2021-06-07 12:39 UTC
Labels: bug, duplicate
