### ISSUE TITLE
Dump of multi track CD-XA doesn’t match a dump from DIC

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#313] opened 2020-03-15 07:26 UTC
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

A dump of a CD-XA disc with multiple tracks created by Aaru doesn’t match one created by DIC. The disc has a single session. The compare command finds three different sectors between the two images. Due to an unreliable internet connection, there may be delays in getting all of the logs and files uploaded. Media info of the disc: https://pastebin.com/JUZUDc2E

**Comment by FakeShemp** [comment] 2020-03-15 12:45
Can you check if it's the same issue as #309 ?

**Comment by SilasLaspada** [comment] 2020-03-16 22:34
Does seem to be the same issue as #309 because three sector towards the end of the image are mostly zeroed out. I also found that the same issue affects a single-track CD-DA disc I have that has CD-Text.

**Comment by claunia** [comment] 2020-04-03 01:40
Duplicate of #309

**Closed by claunia** 2020-04-03 01:40 UTC
Labels: duplicate
