### ISSUE TITLE
Aaru dump of disc has 3 unknown sectors

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#657] opened 2021-09-01 09:39 UTC
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: ASUS 
* **Model**: BW-16D1HT
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [X] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

When dumping a specific CD, verify says that the output image has 3 unknown sectors. This dump matches a dump made by DIC in all but those 3 sectors, where the differing sectors are 0'd out in the DIC dump, but contain some kind of data in the Aaru dump.

### Exact command line used:

`aaru i verify .\DAG_DEMO.aaruf`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+10d286ad built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2021 Natalia Portillo

Disc image checksums are correct
All sector checksums are correct
Total sectors........... 14853
Total errors............ 0
Total unknowns.......... 3
Total errors+unknowns... 3
```

### Media details

Daggerfall Interactive Preview
https://we.tl/t-dLDaIigHBG

**Comment by TheRogueArchivist** [comment] 2021-09-06 03:03
Duplicate of #604

**Closed by TheRogueArchivist** 2021-09-06 03:03 UTC
Labels: bug
