### ISSUE TITLE
Aaru identifies a CD-i Ready disc as CDDA

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#303] opened 2020-03-11 06:02 UTC
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Xubuntu 19.10...
* [X] ...in 64-bit

### Description
Aaru identifies a CD-i Ready disc as CDDA instead of CDI. Media info of the disc: https://pastebin.com/qcHHsx46

**Comment by claunia** [comment] 2020-03-11 11:04
Duplicate of #294

**Closed by claunia** 2020-03-11 11:04 UTC
Labels: duplicate
